server {
    listen 80;

    location /child/ {
        proxy_pass http://child-service:8080/;
    }

    location /cms/ {
        proxy_pass http://cms:8080/;
    }

    location /analysis/ {
        proxy_pass http://analysis-service:8080/;
    }

    location /sync/ {
        proxy_pass http://sync-service:8080/;
    }

    location /subscription/ {
        proxy_pass http://subscription-service:8080/;
    }

    location /gaming/ {
        proxy_pass http://gaming-service:8080/;
    }
}